package com.next.game.animation;

public enum AnimationState {
    IDLE,
    IDLE_UP, IDLE_DOWN, IDLE_LEFT, IDLE_RIGHT,
    WALK_UP, WALK_DOWN, WALK_LEFT, WALK_RIGHT,
    HURT_UP, HURT_DOWN, HURT_LEFT, HURT_RIGHT,
    ATTACK_UP, ATTACK_DOWN, ATTACK_LEFT, ATTACK_RIGHT,
    DEAD
}
